/** @file src/table/sound.c Sound file tables. */

#include <cstdio>
#include "../table/sound.h"

#define ADD_MUSIC_INFO(FILENAME, TRACK, SONGNAME) { SONGNAME, FILENAME, TRACK }

MusicInfo g_table_music[MUSICID_MAX] =
{
	ADD_MUSIC_INFO("dune1.ADL",  8,  NULL), /* Stop */
	ADD_MUSIC_INFO("dune0.ADL",  4, "Title Screen"),
	ADD_MUSIC_INFO("dune0.ADL",  2, "Introduction"),
	ADD_MUSIC_INFO("dune7.ADL",  6, "Hope Fades"),
	ADD_MUSIC_INFO("dune16.ADL", 7, "Destructive Minds"),
	ADD_MUSIC_INFO("dune16.ADL", 8, "The Long Sleep"),
	ADD_MUSIC_INFO("dune20.ADL", 2, "Credits"),
	ADD_MUSIC_INFO("dune7.ADL",  2, "Arid Sands"),
	ADD_MUSIC_INFO("dune7.ADL",  3, "The Council"),
	ADD_MUSIC_INFO("dune7.ADL",  4, "Ordos Briefing"),
	ADD_MUSIC_INFO("dune8.ADL",  3, "Victory 2 (Harkonnen)"),
	ADD_MUSIC_INFO("dune8.ADL",  2, "Victory (Atreides)"),
	ADD_MUSIC_INFO("dune17.ADL", 4, "Abuse (Ordos)"),
	ADD_MUSIC_INFO("dune1.ADL",  4, "Death (Harkonnen)"),
	ADD_MUSIC_INFO("dune1.ADL",  5, "Death (Atreides)"),
	ADD_MUSIC_INFO("dune1.ADL",  3, "Death (Ordos)"),
	ADD_MUSIC_INFO("dune19.ADL", 4, "Evil Harkonnens"),
	ADD_MUSIC_INFO("dune19.ADL", 2, "Noble Atreides"),
	ADD_MUSIC_INFO("dune19.ADL", 3, "Insidious Ordos"),
	ADD_MUSIC_INFO("dune1.ADL",  6, "The Building of a Dynasty"),
	ADD_MUSIC_INFO("dune2.ADL",  6, "Dark Technology"),
	ADD_MUSIC_INFO("dune3.ADL",  6, "Rulers of Arrakis"),
	ADD_MUSIC_INFO("dune4.ADL",  6, "Desert of Doom"),
	ADD_MUSIC_INFO("dune5.ADL",  6, "Faithful Warriors"),
	ADD_MUSIC_INFO("dune6.ADL",  6, "Spice Melange"),
	ADD_MUSIC_INFO("dune9.ADL",  4, "The Prophecy, Part I"),
	ADD_MUSIC_INFO("dune9.ADL",  5, "The Prophecy, Part II"),
	ADD_MUSIC_INFO("dune18.ADL", 6, "For Those Fallen"),
	ADD_MUSIC_INFO("dune1.ADL",  2, "Choose Your House"),
	ADD_MUSIC_INFO("dune10.ADL", 7, "Into the Heat"),
	ADD_MUSIC_INFO("dune11.ADL", 7, "Epic War"),
	ADD_MUSIC_INFO("dune12.ADL", 7, "Humans Fall"),
	ADD_MUSIC_INFO("dune13.ADL", 7, "Adrenaline Rush"),
	ADD_MUSIC_INFO("dune14.ADL", 7, "Only the Strongest Survives"),
	ADD_MUSIC_INFO("dune15.ADL", 7, "Marching Towards the End")
};

/** Available voices. */
const SoundData g_table_voices[SAMPLEID_MAX]
{
	{"+VSCREAM1.VOC", 11}, /*   0 */
	{"+EXSAND.VOC", 10}, /*   1 */
	{"+ROCKET.VOC", 11}, /*   2 */
	{"+BUTTON.VOC", 10}, /*   3 */
	{"+VSCREAM5.VOC", 11}, /*   4 */
	{"+CRUMBLE.VOC", 15}, /*   5 */
	{"+EXSMALL.VOC", 9}, /*   6 */
	{"+EXMED.VOC", 10}, /*   7 */
	{"+EXLARGE.VOC", 14}, /*   8 */
	{"+EXCANNON.VOC", 11}, /*   9 */
	{"+GUNMULTI.VOC", 9}, /*  10 */
	{"+GUN.VOC", 10}, /*  11 */
	{"+EXGAS.VOC", 10}, /*  12 */
	{"+EXDUD.VOC", 10}, /*  13 */
	{"+VSCREAM2.VOC", 11}, /*  14 */
	{"+VSCREAM3.VOC", 11}, /*  15 */
	{"+VSCREAM4.VOC", 11}, /*  16 */
	{"+%cAFFIRM.VOC", 15}, /*  17 */
	{"+%cREPORT1.VOC", 15}, /*  18 */
	{"+%cREPORT2.VOC", 15}, /*  19 */
	{"+%cREPORT3.VOC", 15}, /*  20 */
	{"+%cOVEROUT.VOC", 15}, /*  21 */
	{"+%cMOVEOUT.VOC", 15}, /*  22 */
	{"?POPPA.VOC", 15}, /*  23 */
	{"?SANDBUG.VOC", 15}, /*  24 */
	{"+STATICP.VOC", 10}, /*  25 */
	{"+WORMET3P.VOC", 16}, /*  26 */
	{"+MISLTINP.VOC", 10}, /*  27 */
	{"+SQUISH2.VOC", 12}, /*  28 */
	{"%cENEMY.VOC", 20}, /*  29 */
	{"%cHARK.VOC", 20}, /*  30 */
	{"%cATRE.VOC", 20}, /*  31 */
	{"%cORDOS.VOC", 20}, /*  32 */
	{"%cFREMEN.VOC", 20}, /*  33 */
	{"%cSARD.VOC", 20}, /*  34 */
	{"%cMERC.VOC", 20}, /*  35 */
	{"%cUNIT.VOC", 20}, /*  36 */
	{"%cSTRUCT.VOC", 20}, /*  37 */
	{"%cONE.VOC", 19}, /*  38 */
	{"%cTWO.VOC", 19}, /*  39 */
	{"%cTHREE.VOC", 19}, /*  40 */
	{"%cFOUR.VOC", 19}, /*  41 */
	{"%cFIVE.VOC", 19}, /*  42 */
	{"%cCONST.VOC", 20}, /*  43 */
	{"%cRADAR.VOC", 20}, /*  44 */
	{"%cOFF.VOC", 20}, /*  45 */
	{"%cON.VOC", 20}, /*  46 */
	{"%cFRIGATE.VOC", 20}, /*  47 */
	{"?%cARRIVE.VOC", 20}, /*  48 */
	{"%cWARNING.VOC", 20}, /*  49 */
	{"%cSABOT.VOC", 20}, /*  50 */
	{"%cMISSILE.VOC", 20}, /*  51 */
	{"%cBLOOM.VOC", 20}, /*  52 */
	{"%cDESTROY.VOC", 20}, /*  53 */
	{"%cDEPLOY.VOC", 20}, /*  54 */
	{"%cAPPRCH.VOC", 20}, /*  55 */
	{"%cLOCATED.VOC", 20}, /*  56 */
	{"%cNORTH.VOC", 20}, /*  57 */
	{"%cEAST.VOC", 20}, /*  58 */
	{"%cSOUTH.VOC", 20}, /*  59 */
	{"%cWEST.VOC", 20}, /*  60 */
	{"?%cWIN.VOC", 20}, /*  61 */
	{"?%cLOSE.VOC", 20}, /*  62 */
	{"%cLAUNCH.VOC", 20}, /*  63 */
	{"%cATTACK.VOC", 20}, /*  64 */
	{"%cVEHICLE.VOC", 20}, /*  65 */
	{"%cREPAIR.VOC", 20}, /*  66 */
	{"%cHARVEST.VOC", 20}, /*  67 */
	{"%cWORMY.VOC", 20}, /*  68 */
	{"%cCAPTURE.VOC", 20}, /*  69 */
	{"%cNEXT.VOC", 20}, /*  70 */
	{"%cNEXT2.VOC", 20}, /*  71 */
	{"/BLASTER.VOC", 10}, /*  72 */
	{"/GLASS6.VOC", 10}, /*  73 */
	{"/LIZARD1.VOC", 10}, /*  74 */
	{"/FLESH.VOC", 10}, /*  75 */
	{"/CLICK.VOC", 10}, /*  76 */
	{"-3HOUSES.VOC", 12}, /*  77 */
	{"-ANDNOW.VOC", 12}, /*  78 */
	{"-ARRIVED.VOC", 12}, /*  79 */
	{"-BATTLE.VOC", 12}, /*  80 */
	{"-BEGINS.VOC", 12}, /*  81 */
	{"-BLDING.VOC", 12}, /*  82 */
	{"-CONTROL2.VOC", 12}, /*  83 */
	{"-CONTROL3.VOC", 12}, /*  84 */
	{"-CONTROL4.VOC", 12}, /*  85 */
	{"-CONTROLS.VOC", 12}, /*  86 */
	{"-DUNE.VOC", 12}, /*  87 */
	{"-DYNASTY.VOC", 12}, /*  88 */
	{"-EACHHOME.VOC", 12}, /*  89 */
	{"-EANDNO.VOC", 12}, /*  90 */
	{"-ECONTROL.VOC", 12}, /*  91 */
	{"-EHOUSE.VOC", 12}, /*  92 */
	{"-EMPIRE.VOC", 12}, /*  93 */
	{"-EPRODUCE.VOC", 12}, /*  94 */
	{"-ERULES.VOC", 12}, /*  95 */
	{"-ETERRIT.VOC", 12}, /*  96 */
	{"-EMOST.VOC", 12}, /*  97 */
	{"-ENOSET.VOC", 12}, /*  98 */
	{"-EVIL.VOC", 12}, /*  99 */
	{"-HARK.VOC", 12}, /* 100 */
	{"-HOME.VOC", 12}, /* 101 */
	{"-HOUSE2.VOC", 12}, /* 102 */
	{"-INSID.VOC", 12}, /* 103 */
	{"-KING.VOC", 12}, /* 104 */
	{"-KNOWN.VOC", 12}, /* 105 */
	{"-MELANGE.VOC", 12}, /* 106 */
	{"-NOBLE.VOC", 12}, /* 107 */
	{"?NOW.VOC", 12}, /* 108 */
	{"-OFDUNE.VOC", 12}, /* 109 */
	{"-ORD.VOC", 12}, /* 110 */
	{"-PLANET.VOC", 12}, /* 111 */
	{"-PREVAIL.VOC", 12}, /* 112 */
	{"-PROPOSED.VOC", 12}, /* 113 */
	{"-SANDLAND.VOC", 12}, /* 114 */
	{"-SPICE.VOC", 12}, /* 115 */
	{"-SPICE2.VOC", 12}, /* 116 */
	{"-VAST.VOC", 12}, /* 117 */
	{"-WHOEVER.VOC", 12}, /* 118 */
	{"?YOUR.VOC", 12}, /* 119 */
	{"?FILLER.VOC", 12}, /* 120 */
	{"-DROPEQ2P.VOC", 10}, /* 121 */
	{"/EXTINY.VOC", 10}, /* 122 */
	{"-WIND2BP.VOC", 10}, /* 123 */
	{"-BRAKES2P.VOC", 11}, /* 124 */
	{"-GUNSHOT.VOC", 10}, /* 125 */
	{"-GLASS.VOC", 11}, /* 126 */
	{"-MISSLE8.VOC", 10}, /* 127 */
	{"-CLANK.VOC", 10}, /* 128 */
	{"-BLOWUP1.VOC", 10}, /* 129 */
	{"-BLOWUP2.VOC", 11} /* 130 */
};

/* Map soundID -> sampleID.
 * Sounds mapped to SAMPLE_INVALID are effects.
 */
const SampleID g_table_voiceMapping[SOUNDID_MAX] =
{
	SAMPLE_INVALID, /*   0 */
	SAMPLE_INVALID, /*   1 */
	SAMPLE_INVALID, /*   2 */
	SAMPLE_INVALID, /*   3 */
	SAMPLE_INVALID, /*   4 */
	SAMPLE_INVALID, /*   5 */
	SAMPLE_INVALID, /*   6 */
	SAMPLE_INVALID, /*   7 */
	SAMPLE_INVALID, /*   8 */
	SAMPLE_INVALID, /*   9 */
	SAMPLE_INVALID, /*  10 */
	SAMPLE_INVALID, /*  11 */
	SAMPLE_INVALID, /*  12 */
	SAMPLE_INVALID, /*  13 */
	SAMPLE_INVALID, /*  14 */
	SAMPLE_INVALID, /*  15 */
	SAMPLE_INVALID, /*  16 */
	SAMPLE_INVALID, /*  17 */
	SAMPLE_INVALID, /*  18 */
	SAMPLE_INVALID, /*  19 */
	SAMPLE_PLACEMENT, /*  20 */
	SAMPLE_INVALID, /*  21 */
	SAMPLE_INVALID, /*  22 */
	SAMPLE_INVALID, /*  23 */
	SAMPLE_DROP_LOAD, /*  24 */
	SAMPLE_INVALID, /*  25 */
	SAMPLE_INVALID, /*  26 */
	SAMPLE_INVALID, /*  27 */
	SAMPLE_INVALID, /*  28 */
	SAMPLE_INVALID, /*  29 */
	SAMPLE_SCREAM1, /*  30 */
	SAMPLE_SCREAM5, /*  31 */
	SAMPLE_SCREAM2, /*  32 */
	SAMPLE_SCREAM3, /*  33 */
	SAMPLE_SCREAM4, /*  34 */
	SAMPLE_SQUISH, /*  35 */
	SAMPLE_INVALID, /*  36 */
	SAMPLE_INVALID, /*  37 */
	SAMPLE_BUTTON, /*  38 */
	SAMPLE_EXPLODE_GAS, /*  39: s_explosion07 */
	SAMPLE_EXPLODE_SAND, /*  40: s_explosion08, s_explosion19 */
	SAMPLE_EXPLODE_MEDIUM, /*  41: s_explosion05, s_explosion09 */
	SAMPLE_ROCKET, /*  42: Death Hand, Launcher, Rocket Turret, Deviator */
	SAMPLE_INVALID, /*  43: Sonic Tank */
	SAMPLE_STRUCTURE_DESTROYED, /*  44 */
	SAMPLE_INVALID, /*  45 */
	SAMPLE_INVALID, /*  46 */
	SAMPLE_INVALID, /*  47 */
	SAMPLE_INVALID, /*  48 */
	SAMPLE_EXPLODE_MEDIUM, /*  49: s_explosion03, s_explosion10, s_explosion15, s_explosion16, s_explosion17 */
	SAMPLE_EXPLODE_SMALL, /*  50: s_explosion02 */
	SAMPLE_EXPLODE_LARGE, /*  51: s_explosion04, s_explosion06, s_explosion11, s_explosion14 */
	SAMPLE_INVALID, /*  52 */
	SAMPLE_INVALID, /*  53 */
	SAMPLE_EXPLODE_TINY, /*  54: s_explosion18 */
	SAMPLE_INVALID, /*  55 */
	SAMPLE_EXPLODE_CANNON, /*  56 */
	SAMPLE_EXPLODE_CANNON, /*  57: Tank, Siege Tank, Devastator Tank */
	SAMPLE_GUN, /*  58: Soldier, Soldiers, Saboteur */
	SAMPLE_MACHINE_GUN, /*  59: Trike, Raider Trike, Quad, Trooper(s) at close range */
	SAMPLE_VOICE_FRAGMENT_CONSTRUCTION_COMPLETE, /*  60 */
	SAMPLE_INVALID, /*  61 */
	SAMPLE_RADAR_STATIC, /*  62 */
	SAMPLE_SANDWORM, /*  63 */
	SAMPLE_MINI_ROCKET, /*  64: Ornithopter, Trooper(s) at long range */
	SAMPLE_BLASTER, /*  65: Harkonnen end game */
	SAMPLE_GLASS, /*  66: Harkonnen end game */
	SAMPLE_LIZARD, /*  67: Ordos end game */
	SAMPLE_FLESH, /*  68: Harkonnen end game */
	SAMPLE_CLICK, /*  69: Harkonnen end game */
	SAMPLE_INVALID, /*  70 */
	SAMPLE_INVALID, /*  71 */
	SAMPLE_INVALID, /*  72 */
	SAMPLE_INVALID, /*  73 */
	SAMPLE_INVALID, /*  74 */
	SAMPLE_INVALID, /*  75 */
	SAMPLE_INVALID, /*  76 */
	SAMPLE_INVALID, /*  77 */
	SAMPLE_INVALID, /*  78 */
	SAMPLE_INVALID, /*  79 */
	SAMPLE_INVALID, /*  80 */
	SAMPLE_INVALID, /*  81 */
	SAMPLE_INVALID, /*  82 */
	SAMPLE_INVALID, /*  83 */
	SAMPLE_INVALID, /*  84 */
	SAMPLE_INVALID, /*  85 */
	SAMPLE_INVALID, /*  86 */
	SAMPLE_INVALID, /*  87 */
	SAMPLE_INVALID, /*  88 */
	SAMPLE_INVALID, /*  89 */
	SAMPLE_INVALID, /*  90 */
	SAMPLE_INVALID, /*  91 */
	SAMPLE_INVALID, /*  92 */
	SAMPLE_INVALID, /*  93 */
	SAMPLE_INVALID, /*  94 */
	SAMPLE_INVALID, /*  95 */
	SAMPLE_INVALID, /*  96 */
	SAMPLE_INVALID, /*  97 */
	SAMPLE_INVALID, /*  98 */
	SAMPLE_INVALID, /*  99 */
	SAMPLE_INVALID, /* 100 */
	SAMPLE_INVALID, /* 101 */
	SAMPLE_INVALID, /* 102 */
	SAMPLE_INVALID, /* 103 */
	SAMPLE_INVALID, /* 104 */
	SAMPLE_INVALID, /* 105 */
	SAMPLE_INVALID, /* 106 */
	SAMPLE_INVALID, /* 107 */
	SAMPLE_INTRO_WIND, /* 108 */
	SAMPLE_INVALID, /* 109 */
	SAMPLE_INTRO_HARVESTER, /* 110 */
	SAMPLE_INVALID, /* 111 */
	SAMPLE_INTRO_FIRE_ORNITHOPTER_TROOPER, /* 112 */
	SAMPLE_INTRO_BREAK_GLASS, /* 113 */
	SAMPLE_INTRO_FIRE_LAUNCHER, /* 114 */
	SAMPLE_INVALID, /* 115 */
	SAMPLE_INVALID, /* 116 */
	SAMPLE_INTRO_CARRYALL_FRIGATE, /* 117 */
	SAMPLE_INTRO_TROOPER_EXPLODE1, /* 118 */
	SAMPLE_INTRO_TROOPER_EXPLODE2 /* 119 */
};

/**
 * Feedback on events and user commands (English audio, viewport message, and sound).
 * @see g_translatedVoice
 */
const Feedback g_feedback[VOICEID_MAX] =
{
	{{(SampleID)0x002B, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x33}, /*  0 */
	{{(SampleID)0x0031, (SampleID)0x001D, (SampleID)0x0024, (SampleID)0x0037, SAMPLE_INVALID}, 0x34}, /*  1 */
	{{(SampleID)0x0031, (SampleID)0x001D, (SampleID)0x0024, (SampleID)0x0037, (SampleID)0x0039}, 0x34}, /*  2 */
	{{(SampleID)0x0031, (SampleID)0x001D, (SampleID)0x0024, (SampleID)0x0037, (SampleID)0x003A}, 0x34}, /*  3 */
	{{(SampleID)0x0031, (SampleID)0x001D, (SampleID)0x0024, (SampleID)0x0037, (SampleID)0x003B}, 0x34}, /*  4 */
	{{(SampleID)0x0031, (SampleID)0x001D, (SampleID)0x0024, (SampleID)0x0037, (SampleID)0x003C}, 0x34}, /*  5 */
	{{(SampleID)0x0031, (SampleID)0x001E, (SampleID)0x0024, (SampleID)0x0037, SAMPLE_INVALID}, 0x35}, /*  6 */
	{{(SampleID)0x0031, (SampleID)0x001F, (SampleID)0x0024, (SampleID)0x0037, SAMPLE_INVALID}, 0x36}, /*  7 */
	{{(SampleID)0x0031, (SampleID)0x0020, (SampleID)0x0024, (SampleID)0x0037, SAMPLE_INVALID}, 0x37}, /*  8 */
	{{(SampleID)0x0031, (SampleID)0x0021, (SampleID)0x0024, (SampleID)0x0037, SAMPLE_INVALID}, 0x38}, /*  9 */
	{{(SampleID)0x0031, (SampleID)0x0022, (SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID}, 0x39}, /* 10 */
	{{(SampleID)0x0031, (SampleID)0x0023, (SampleID)0x0024, (SampleID)0x0037, SAMPLE_INVALID}, 0x3A}, /* 11 */
	{{(SampleID)0x0031, (SampleID)0x0032, (SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID}, 0x3B}, /* 12 */
	{{(SampleID)0x001D, (SampleID)0x0024, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 13 */
	{{(SampleID)0x001E, (SampleID)0x0024, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x3C}, /* 14 */
	{{(SampleID)0x001F, (SampleID)0x0024, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x3D}, /* 15 */
	{{(SampleID)0x0020, (SampleID)0x0024, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x3E}, /* 16 */
	{{(SampleID)0x0021, (SampleID)0x0024, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x3F}, /* 17 */
	{{(SampleID)0x0022, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x40}, /* 18 */
	{{(SampleID)0x0023, (SampleID)0x0024, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x41}, /* 19 */
	{{(SampleID)0x0032, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 20 */
	{{(SampleID)0x001D, (SampleID)0x0025, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 21 */
	{{(SampleID)0x001E, (SampleID)0x0025, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x42}, /* 22 */
	{{(SampleID)0x001F, (SampleID)0x0025, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x43}, /* 23 */
	{{(SampleID)0x0020, (SampleID)0x0025, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x44}, /* 24 */
	{{(SampleID)0x0021, (SampleID)0x0025, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x45}, /* 25 */
	{{(SampleID)0x0022, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x46}, /* 26 */
	{{(SampleID)0x0023, (SampleID)0x0025, (SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID}, 0x47}, /* 27 */
	{{(SampleID)0x002C, (SampleID)0x002E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 28 */
	{{(SampleID)0x002C, (SampleID)0x002D, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 29 */
	{{(SampleID)0x001E, (SampleID)0x0024, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x48}, /* 30 */
	{{(SampleID)0x001F, (SampleID)0x0024, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x49}, /* 31 */
	{{(SampleID)0x0020, (SampleID)0x0024, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x4A}, /* 32 */
	{{(SampleID)0x0021, (SampleID)0x0024, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x4B}, /* 33 */
	{{(SampleID)0x0022, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x4C}, /* 34 */
	{{(SampleID)0x0023, (SampleID)0x0024, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x4D}, /* 35 */
	{{(SampleID)0x0034, (SampleID)0x0038, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 36 */
	{{(SampleID)0x0031, (SampleID)0x0044, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x4E}, /* 37 */
	{{(SampleID)0x002F, (SampleID)0x0030, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x50}, /* 38 */
	{{(SampleID)0x0031, (SampleID)0x0033, (SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID}, 0x51}, /* 39 */
	{{(SampleID)0x003D, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 40 */
	{{(SampleID)0x003E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 41 */
	{{(SampleID)0x0033, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 42 */

	/* The countdown ticking sound 0x002E repeats five times already. */
	{{(SampleID)0x0026, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 43 */
	{{(SampleID)0x0027, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 44 */
	{{(SampleID)0x0028, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 45 */
	{{(SampleID)0x0029, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 46 */
	{{(SampleID)0x002A, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 47 */

	{{(SampleID)0x0040, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x5A}, /* 48 */
	{{(SampleID)0x001E, (SampleID)0x0024, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID}, 0x9A}, /* 49 */
	{{(SampleID)0x001F, (SampleID)0x0024, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID}, 0x9B}, /* 50 */
	{{(SampleID)0x0020, (SampleID)0x0024, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID}, 0x9C}, /* 51 */
	{{(SampleID)0x0021, (SampleID)0x0024, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID}, 0x9D}, /* 52 */
	{{(SampleID)0x0022, (SampleID)0x0024, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID}, 0x9E}, /* 53 */
	{{(SampleID)0x0023, (SampleID)0x0024, (SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID}, 0x9F}, /* 54 */
	{{(SampleID)0x001E, (SampleID)0x0041, (SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID}, 0xA2}, /* 55 */
	{{(SampleID)0x001F, (SampleID)0x0041, (SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID}, 0xA3}, /* 56 */
	{{(SampleID)0x0020, (SampleID)0x0041, (SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID}, 0xA4}, /* 57 */
	{{(SampleID)0x0021, (SampleID)0x0041, (SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID}, 0xA5}, /* 58 */
	{{(SampleID)0x0022, (SampleID)0x0041, (SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID}, 0xA6}, /* 59 */
	{{(SampleID)0x0023, (SampleID)0x0041, (SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID}, 0xA7}, /* 60 */
	{{(SampleID)0x0046, (SampleID)0x0047, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 61 */

	{{(SampleID)0x001E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 62 */
	{{(SampleID)0x001F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 63 */
	{{(SampleID)0x0020, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x00}, /* 64 */
	{{SAMPLE_VOICE_FRAGMENT_FREMEN,
		SAMPLE_VOICE_FRAGMENT_APPROACHING,
		SAMPLE_INVALID,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 65 */
	{{SAMPLE_VOICE_FRAGMENT_SARDAUKAR,
		SAMPLE_VOICE_FRAGMENT_DEPLOYED,
		SAMPLE_INVALID,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 66 */
	{{SAMPLE_VOICE_FRAGMENT_MERCENARY,
		SAMPLE_VOICE_FRAGMENT_HAS_ARRIVED,
		SAMPLE_INVALID,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 67 */

	{{(SampleID)0x001E, (SampleID)0x0043, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x93}, /* 68 */
	{{(SampleID)0x001F, (SampleID)0x0043, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x94}, /* 69 */
	{{(SampleID)0x0020, (SampleID)0x0043, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x95}, /* 70 */
	{{(SampleID)0x0021, (SampleID)0x0043, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x96}, /* 71 */
	{{(SampleID)0x0022, (SampleID)0x0043, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x97}, /* 72 */
	{{(SampleID)0x0023, (SampleID)0x0043, (SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID}, 0x98}, /* 73 */

	{{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x01}, /* 74 */
	{{SAMPLE_INTRO_DUNE,
		SAMPLE_INVALID,
		SAMPLE_INVALID,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 75 */
	{{SAMPLE_INTRO_THE_BUILDING,
		SAMPLE_INTRO_OF_A_DYNASTY,
		SAMPLE_INVALID,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x01}, /* 76 */
	{{(SampleID)0x006F, (SampleID)0x0069, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 77 */
	{{(SampleID)0x0072, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 78 */
	{{(SampleID)0x0065, (SampleID)0x0073, (SampleID)0x006A, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 79 */
	{{(SampleID)0x0074, (SampleID)0x0056, (SampleID)0x005D, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 80 */
	{{(SampleID)0x0076, (SampleID)0x0053, (SampleID)0x0054, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 81 */
	{{(SampleID)0x0068, (SampleID)0x0071, (SampleID)0x0059, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 82 */
	{{(SampleID)0x005C, (SampleID)0x005E, (SampleID)0x0061, (SampleID)0x005B, SAMPLE_INVALID}, 0x02}, /* 83 */
	{{(SampleID)0x0062, (SampleID)0x0060, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 84 */
	{{(SampleID)0x005A, (SampleID)0x005F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 85 */
	{{(SampleID)0x0075, (SampleID)0x004F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 86 */
	{{(SampleID)0x004E, (SampleID)0x004D, (SampleID)0x0055, (SampleID)0x006D, SAMPLE_INVALID}, 0x01}, /* 87 */
	{{(SampleID)0x006B, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 88 */
	{{(SampleID)0x0067, (SampleID)0x006E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 89 */
	{{(SampleID)0x0063, (SampleID)0x0064, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 90 */
	{{(SampleID)0x0066, (SampleID)0x0070, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x02}, /* 91 */
	{{(SampleID)0x0077, (SampleID)0x0050, (SampleID)0x0051, SAMPLE_INVALID, SAMPLE_INVALID}, 0x01}, /* 92 */
	{{(SampleID)0x006C, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, 0x01}, /* 93 */

	{{SAMPLE_VOICE_FRAGMENT_ENEMY,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 94 */
	{{SAMPLE_VOICE_FRAGMENT_HARKONNEN,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 95 */
	{{SAMPLE_VOICE_FRAGMENT_ATREIDES,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 96 */
	{{SAMPLE_VOICE_FRAGMENT_ORDOS,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 97 */
	{{SAMPLE_VOICE_FRAGMENT_FREMEN,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 98 */
	{{SAMPLE_VOICE_FRAGMENT_SARDAUKAR,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 99 */
	{{SAMPLE_VOICE_FRAGMENT_MERCENARY,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, 0x00}, /* 100 */
};

/** Translated audio feedback of events and user commands. */
const SampleID g_translatedVoice[VOICEID_MAX][NUM_SPEECH_PARTS] = {
	{SAMPLE_VOICE_FRAGMENT_CONSTRUCTION_COMPLETE, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  0 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  1 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  2 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  3 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  4 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  5 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  6 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  7 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  8 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /*  9 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 10 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ENEMY, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 11 */
	{SAMPLE_VOICE_FRAGMENT_WARNING, SAMPLE_VOICE_FRAGMENT_ORDOS, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 12 */
	{SAMPLE_VOICE_FRAGMENT_UNIT, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 13 */
	{(SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 14 */
	{(SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 15 */
	{(SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 16 */
	{(SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 17 */
	{(SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 18 */
	{(SampleID)0x0037, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 19 */
	{(SampleID)0x0035, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 20 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 21 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 22 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 23 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 24 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 25 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 26 */
	{(SampleID)0x0025, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 27 */
	{(SampleID)0x002E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 28 */
	{(SampleID)0x002D, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 29 */
	{(SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 30 */
	{(SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 31 */
	{(SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 32 */
	{(SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 33 */
	{(SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 34 */
	{(SampleID)0x0036, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 35 */
	{(SampleID)0x0034, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 36 */
	{(SampleID)0x0031, (SampleID)0x0044, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 37 */
	{(SampleID)0x002F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 38 */
	{(SampleID)0x0031, (SampleID)0x0033, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 39 */
	{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 40 */
	{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 41 */
	{(SampleID)0x003F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 42 */
	{(SampleID)0x0026, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 43 */
	{(SampleID)0x0027, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 44 */
	{(SampleID)0x0028, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 45 */
	{(SampleID)0x0029, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 46 */
	{(SampleID)0x002A, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 47 */
	{(SampleID)0x0040, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 48 */
	{(SampleID)0x0041, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 49 */
	{(SampleID)0x0041, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 50 */
	{(SampleID)0x0041, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 51 */
	{(SampleID)0x0041, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 52 */
	{(SampleID)0x0041, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 53 */
	{(SampleID)0x0041, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 54 */
	{(SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 55 */
	{(SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 56 */
	{(SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 57 */
	{(SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 58 */
	{(SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 59 */
	{(SampleID)0x0042, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 60 */
	{(SampleID)0x0046, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 61 */
	{(SampleID)0x001E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 62 */
	{(SampleID)0x001F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 63 */
	{(SampleID)0x0020, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 64 */
	{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 65 */
	{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 66 */
	{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 67 */
	{(SampleID)0x0043, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 68 */
	{(SampleID)0x0043, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 69 */
	{(SampleID)0x0043, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 70 */
	{(SampleID)0x0043, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 71 */
	{(SampleID)0x0043, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 72 */
	{(SampleID)0x0043, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 73 */
	{(SampleID)0xFFFF, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 74 */
	{(SampleID)0x0057, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 75 */
	{(SampleID)0x0052, (SampleID)0x0058, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 76 */
	{(SampleID)0x006F, (SampleID)0x0069, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 77 */
	{(SampleID)0x0072, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 78 */
	{(SampleID)0x0065, (SampleID)0x0073, (SampleID)0x006A, SAMPLE_INVALID, SAMPLE_INVALID}, /* 79 */
	{(SampleID)0x0074, (SampleID)0x0056, (SampleID)0x005D, SAMPLE_INVALID, SAMPLE_INVALID}, /* 80 */
	{(SampleID)0x0076, (SampleID)0x0053, (SampleID)0x0054, SAMPLE_INVALID, SAMPLE_INVALID}, /* 81 */
	{(SampleID)0x0068, (SampleID)0x0071, (SampleID)0x0059, SAMPLE_INVALID, SAMPLE_INVALID}, /* 82 */
	{(SampleID)0x005C, (SampleID)0x005E, (SampleID)0x0061, (SampleID)0x005B, SAMPLE_INVALID}, /* 83 */
	{(SampleID)0x0062, (SampleID)0x0060, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 84 */
	{(SampleID)0x005A, (SampleID)0x005F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 85 */
	{(SampleID)0x0075, (SampleID)0x004F, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 86 */
	{(SampleID)0x004E, (SampleID)0x004D, (SampleID)0x0055, (SampleID)0x006D, SAMPLE_INVALID}, /* 87 */
	{(SampleID)0x006B, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 88 */
	{(SampleID)0x0067, (SampleID)0x006E, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 89 */
	{(SampleID)0x0063, (SampleID)0x0064, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 90 */
	{(SampleID)0x0066, (SampleID)0x0070, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 91 */
	{(SampleID)0x0077, (SampleID)0x0050, (SampleID)0x0051, SAMPLE_INVALID, SAMPLE_INVALID}, /* 92 */
	{(SampleID)0x006C, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID, SAMPLE_INVALID}, /* 93 */

	{SAMPLE_VOICE_FRAGMENT_ENEMY,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 94 */
	{SAMPLE_VOICE_FRAGMENT_HARKONNEN,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 95 */
	{SAMPLE_VOICE_FRAGMENT_ATREIDES,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 96 */
	{SAMPLE_VOICE_FRAGMENT_ORDOS,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 97 */
	{SAMPLE_VOICE_FRAGMENT_FREMEN,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 98 */
	{SAMPLE_VOICE_FRAGMENT_SARDAUKAR,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 99 */
	{SAMPLE_VOICE_FRAGMENT_MERCENARY,
		SAMPLE_VOICE_FRAGMENT_STRUCTURE,
		SAMPLE_VOICE_FRAGMENT_CAPTURED,
		SAMPLE_INVALID,
		SAMPLE_INVALID}, /* 100 */
};
