/** @file src/table/widgetinfo.c WidgetInfo file table. */

#include "enum_string.h"
#include "widgetinfo.h"
#include "../gui/widget.h"
#include "../input/scancode.h"
#include "../newui/menubar.h"
#include "../newui/viewportnewui.h"

WidgetInfo g_table_gameWidgetInfo[GAME_WIDGET_MAX + 1] =
{
	{/* 0 */
		/* index       */ 1,
		/* clickProc   */ &MenuBar_ClickMentat,
		/* shortcut    */ SCANCODE_F1,
		/* flags       */ 1237,
		/* spriteID    */ 7,
		/* offsetX     */ 16,
		/* offsetY     */ 1,
		/* width       */ 78,
		/* height      */ 16,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MENUBAR,
	},
	{/* 1 */
		/* index       */ 2,
		/* clickProc   */ &MenuBar_ClickOptions,
		/* shortcut    */ SCANCODE_F2,
		/* flags       */ 1237,
		/* spriteID    */ 9,
		/* offsetX     */ 104,
		/* offsetY     */ 1,
		/* width       */ 78,
		/* height      */ 16,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MENUBAR,
	},
	{/* 2 */
		/* index       */ 3,
		/* clickProc   */ &GUI_Widget_Name_Click,
		/* shortcut    */ 0,
		/* flags       */ 17605,
		/* spriteID    */ -1,
		/* offsetX     */ 256 - 240,
		/* offsetY     */ 42 - 40,
		/* width       */ 64,
		/* height      */ 6,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 3 */
		/* index       */ 6,
		/* clickProc   */ &GUI_Widget_Picture_Click,
		/* shortcut    */ SCANCODE_F3,
		/* flags       */ 17605,
		/* spriteID    */ -4,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 51 - 40,
		/* width       */ 32,
		/* height      */ 24,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 4 */
		/* index       */ 4,
		/* clickProc   */ &GUI_Widget_RepairUpgrade_Click,
		/* shortcut    */ 0,
		/* flags       */ 17605,
		/* spriteID    */ -2,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 76 - 40,
		/* width       */ 60,
		/* height      */ 10,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 5 */
		/* index       */ 5,
		/* clickProc   */ &GUI_Widget_SpriteTextButton_Click,
		/* shortcut    */ SCANCODE_P,
		/* flags       */ 17605,
		/* spriteID    */ -3,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 87 - 40,
		/* width       */ 60,
		/* height      */ 35,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 6 */
		/* index       */ 7,
		/* clickProc   */ &GUI_Widget_Cancel_Click,
		/* shortcut    */ SCANCODE_ESCAPE,
		/* flags       */ 17605,
		/* spriteID    */ -2,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 110 - 40,
		/* width       */ 58,
		/* height      */ 11,
		/* stringID    */ STR_CANCEL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 7 */
		/* index       */ 8,
		/* clickProc   */ &GUI_Widget_TextButton_Click,
		/* shortcut    */ 0,
		/* flags       */ 17605,
		/* spriteID    */ -2,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 77 - 40,
		/* width       */ 60,
		/* height      */ 10,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 8 */
		/* index       */ 9,
		/* clickProc   */ &GUI_Widget_TextButton_Click,
		/* shortcut    */ 0,
		/* flags       */ 17605,
		/* spriteID    */ -2,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 88 - 40,
		/* width       */ 60,
		/* height      */ 10,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 9 */
		/* index       */ 10,
		/* clickProc   */ &GUI_Widget_TextButton_Click,
		/* shortcut    */ 0,
		/* flags       */ 17605,
		/* spriteID    */ -2,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 99 - 40,
		/* width       */ 60,
		/* height      */ 10,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 10 */
		/* index       */ 11,
		/* clickProc   */ &GUI_Widget_TextButton_Click,
		/* shortcut    */ 0,
		/* flags       */ 17605,
		/* spriteID    */ -2,
		/* offsetX     */ 258 - 240,
		/* offsetY     */ 110 - 40,
		/* width       */ 60,
		/* height      */ 10,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 11 */
		/* index       */ 39,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x0F40, /* Was 0x4F00 == 20224.  Scroll up widget needed for screen edge scrolling. */
		/* spriteID    */ -1,
		/* offsetX     */ 0,
		/* offsetY     */ 24,
		/* width       */ 240,
		/* height      */ 16,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MAIN,
	},
	{/* 12 */
		/* index       */ 40,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x0F40, /* Was 0x4F00 == 20224.  Scroll right widget needed for screen edge scrolling. */
		/* spriteID    */ -1,
		/* offsetX     */ 240,
		/* offsetY     */ 40,
		/* width       */ 10,
		/* height      */ 160,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MAIN,
	},
	{/* 13 */
		/* index       */ 41,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x0F40, /* Was 0x4F00 == 20224. */
		/* spriteID    */ -1,
		/* offsetX     */ 0,
		/* offsetY     */ 40,
		/* width       */ 2,
		/* height      */ 160,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MAIN,
	},
	{/* 14 */
		/* index       */ 42,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x0F40, /* Was 0x4F00 == 20224.  Scroll down widget needed for screen edge scrolling due to minimap. */
		/* spriteID    */ -1,
		/* offsetX     */ 0,
		/* offsetY     */ 198,
		/* width       */ 240,
		/* height      */ 2,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MAIN,
	},
	{/* 15 */
		/* index       */ 43,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x4F40, /* Was 0x4F00 == 20224. */
		/* spriteID    */ -1,
		/* offsetX     */ 0,
		/* offsetY     */ 40,
		/* width       */ 240,
		/* height      */ 160,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_VIEWPORT,
	},
	{/* 16 */
		/* index       */ 44,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x4F40, /* 0x4F40 == 20288. */
		/* spriteID    */ -1,
		/* offsetX     */ 256 - 240,
		/* offsetY     */ 136 - 40,
		/* width       */ 64,
		/* height      */ 64,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_SIDEBAR,
	},
	{/* 17 */
		/* index       */ 45,
		/* clickProc   */ &Viewport_Click,
		/* shortcut    */ 0,
		/* flags       */ 0x4F40, /* Was 0x4F00 == 20224. */
		/* spriteID    */ -1,
		/* offsetX     */ 0,
		/* offsetY     */ 0,
		/* width       */ 320,
		/* height      */ 200,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MAIN,
	},
	{/* 18 */
		/* index       */ -1,
		/* clickProc   */ NULL,
		/* shortcut    */ 0,
		/* flags       */ 0,
		/* spriteID    */ 0,
		/* offsetX     */ 0,
		/* offsetY     */ 0,
		/* width       */ 0,
		/* height      */ 0,
		/* stringID    */ STR_NULL,
		/* div         */ SCREENDIV_MAIN,
	}
};
